# ==========================================
# CONFIGURACIÓN GENERAL - SECUREBANK TEST
# ==========================================

# Aplicación
app.url=https://www.saucedemo.com
app.timeout=15
app.title=Swag Labs

# Browser
browser=chrome
browser.headless=false
browser.window.maximize=true

# Credenciales de prueba
user.standard=standard_user
user.locked=locked_out_user
user.problem=problem_user
password.secret=secret_sauce

# API
api.base.url=https://reqres.in/api
api.key=reqres-free-v1

# Entorno
environment=qa
build.number=${BUILD_NUMBER:-local}

# Reportes
screenshot.on.failure=true
screenshot.path=target/screenshots
allure.results.path=target/allure-results
